apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: workbc-email-preview-template
labels:
  template: workbc-email-preview
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      annotations:
        name: ${NAME}$-frontend
        app.openshift.io/vcs-ref: ${SOURCE_REPOSITORY_REF}
        app.openshift.io/vcs-uri: ${SOURCE_REPOSITORY_URL}
      name: ${NAME}$-frontend
      creationTimestamp: null
      namespace: ${NAMESPACE}
      labels:
        shared: true
        app: ${NAME}
        app.kubernetes.io/component: ${NAME}
        app.kubernetes.io/instance: ${NAME}
        app.kubernetes.io/name: ${NAME}
        app.openshift.io/runtime: nodejs
        app.openshift.io/runtime-version: ${NODE_JS_VERSION}
    spec:
      lookupPolicy:
        local: false
  - apiVersion: v1
    kind: ImageStream
    metadata:
      annotations:
        name: ${NAME}-backend
        app.openshift.io/vcs-ref: ${SOURCE_REPOSITORY_REF}
        app.openshift.io/vcs-uri: ${SOURCE_REPOSITORY_URL}
      name: ${NAME}-backend
      creationTimestamp: null
      namespace: ${NAMESPACE}
      labels:
        shared: true
        app: ${NAME}
        app.kubernetes.io/component: ${NAME}
        app.kubernetes.io/instance: ${NAME}
        app.kubernetes.io/name: ${NAME}
        app.openshift.io/runtime: nodejs
        app.openshift.io/runtime-version: ${NODE_JS_VERSION}
    spec:
      lookupPolicy:
        local: false
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      annotations:
        name: ${NAME}-backend
        app.openshift.io/vcs-ref: ${SOURCE_REPOSITORY_REF}
        app.openshift.io/vcs-uri: ${SOURCE_REPOSITORY_URL}
      name: ${NAME}-backend
      creationTimestamp: null
      namespace: ${NAMESPACE}
      labels:
        app: ${NAME}
        app.openshift.io/runtime: nodejs
    spec:
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}-backend:${TAG}
      successfulBuildsHistoryLimit: 5
      failedBuildsHistoryLimit: 5
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: Dockerfile
      postCommit: {}
      resources:
        requests:
          cpu: 1
          memory: 2Gi
        limits:
          cpu: 2
          memory: 4Gi
      source:
        type: Git
        git:
          uri: ${SOURCE_REPOSITORY_URL}
          ref: ${SOURCE_REPOSITORY_REF}
        contextDir: /packages/backend
      triggers:
        - type: ConfigChange
        - imageChange: {}
          type: ImageChange
      runPolicy: Serial
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      annotations:
        name: ${NAME}-frontend
        app.openshift.io/vcs-ref: ${SOURCE_REPOSITORY_REF}
        app.openshift.io/vcs-uri: ${SOURCE_REPOSITORY_URL}
      name: ${NAME}-frontend
      creationTimestamp: null
      namespace: ${NAMESPACE}
      labels:
        app: ${NAME}
        app.openshift.io/runtime: nodejs
    spec:
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}-frontend:${TAG}
      successfulBuildsHistoryLimit: 5
      failedBuildsHistoryLimit: 5
      strategy:
        type: Docker
        dockerStrategy:
          env:
            - name: VITE_APP_KEYCLOAK_REALM
              value: ${VITE_APP_KEYCLOAK_REALM}
            - name: VITE_APP_KEYCLOAK_CLIENT_ID
              value: ${VITE_APP_KEYCLOAK_CLIENT_ID}
            - name: VITE_APP_KEYCLOAK_URL
              value: ${VITE_APP_KEYCLOAK_URL}
            - name: VITE_APP_API_URL
              value: ${VITE_APP_API_URL}
          dockerfilePath: Dockerfile
      postCommit: {}
      resources:
        requests:
          cpu: 1
          memory: 2Gi
        limits:
          cpu: 2
          memory: 4Gi
      source:
        type: Git
        git:
          uri: ${SOURCE_REPOSITORY_URL}
          ref: ${SOURCE_REPOSITORY_REF}
        contextDir: /packages/frontend
      triggers:
        - type: ConfigChange
        - imageChange: {}
          type: ImageChange
      runPolicy: Serial
parameters:
  - description: A name used for all objects
    displayName: Name
    name: NAME
    required: true
    value: workbc-email-preview
  - description: The namespace of the project namespace
    displayName: Namespace
    name: NAMESPACE
    required: true
    value: ""
  - description: Tag used for the image tags
    displayName: tag
    name: TAG
    required: true
    value: latest
  - description: SOURCE_REPOSITORY_URL
    displayName: SOURCE_REPOSITORY_URL
    name: SOURCE_REPOSITORY_URL
    required: true
    value: "https://github.com/bcgov/workbc-wage-subsidy"
  - description: SOURCE_REPOSITORY_REF
    displayName: SOURCE_REPOSITORY_REF
    name: SOURCE_REPOSITORY_REF
    required: true
    value: next-claims
  - description: NODE_JS_VERSION
    displayName: NODE_JS_VERSION
    name: NODE_JS_VERSION
    required: true
    value: "18"
  - description: VITE_APP_KEYCLOAK_REALM
    displayName: VITE_APP_KEYCLOAK_REALM
    name: VITE_APP_KEYCLOAK_REALM
    required: true
    value: ""
  - description: VITE_APP_KEYCLOAK_CLIENT_ID
    displayName: VITE_APP_KEYCLOAK_CLIENT_ID
    name: VITE_APP_KEYCLOAK_CLIENT_ID
    required: true
    value: ""
  - description: VITE_APP_KEYCLOAK_URL
    displayName: VITE_APP_KEYCLOAK_URL
    name: VITE_APP_KEYCLOAK_URL
    required: true
    value: ""
  - description: VITE_APP_API_URL
    displayName: VITE_APP_API_URL
    name: VITE_APP_API_URL
    required: true
    value: ""
